### ISSUE TITLE
update pip requirements

### ISSUE THREAD

**Issue by fabricat** [ansible/ansible_collections_azure#441]
The package `azure >= 2.0.0` is indicated as a requirement
Unfortunately, if I try to `pip install azure` I get the following error:

> Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
> Please install the service specific packages prefixed by `azure` needed for your application.

It seems necessary to update the requirements on:
https://github.com/ansible-collections/azure/blob/7b69d0dc58a033638a8c7441d118864641882bac/plugins/doc_fragments/azure.py#L100

**Comment by Fred-sun** [comment]
@fabricat Thank for your contribution this Issue. I will check it!

**Comment by Fred-sun** [comment]
@haiyuazhang https://github.com/ansible-collections/azure/blob/7b69d0dc58a033638a8c7441d118864641882bac/plugins/doc_fragments/azure.py#L100 , I think this package should be azure-cli-core, Please help confirm! Thank you very much!

**Comment by kohtala** [comment]
As an end user, I find requirements management to be very much neglected. I created MicrosoftDocs/azure-dev-docs#509 on documentation. It is difficult to install this for production.

The current requirements are very old. They are lacking over three years of development and maintenance.

```
$ pip install -r https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
...
$ pip list --outdated
Package                           Version Latest Type
--------------------------------- ------- ------ -----
azure-cli-core                    2.11.1  2.23.0 wheel
azure-cli-nspkg                   3.0.2   3.0.4  wheel
azure-common                      1.1.11  1.1.27 wheel
azure-keyvault                    1.0.0a1 4.1.0  wheel
azure-mgmt-authorization          0.51.1  1.0.0  wheel
azure-mgmt-automation             0.1.1   1.0.0  wheel
azure-mgmt-batch                  5.0.1   15.0.0 wheel
azure-mgmt-cdn                    3.0.0   11.0.0 wheel
azure-mgmt-compute                10.0.0  20.0.0 wheel
azure-mgmt-containerinstance      1.4.0   7.0.0  wheel
azure-mgmt-containerregistry      2.0.0   2.8.0  wheel
azure-mgmt-containerservice       9.1.0   15.1.0 wheel
azure-mgmt-core                   1.2.0   1.2.2  wheel
azure-mgmt-cosmosdb               0.5.2   6.3.0  wheel
azure-mgmt-devtestlabs            3.0.0   9.0.0  wheel
azure-mgmt-dns                    2.1.0   8.0.0  wheel
azure-mgmt-hdinsight              0.1.0   7.0.0  wheel
azure-mgmt-iothub                 0.7.0   2.0.0  wheel
azure-mgmt-keyvault               1.1.0   9.0.0  wheel
azure-mgmt-loganalytics           1.0.0   10.0.0 wheel
azure-mgmt-managedservices        1.0.0   6.0.0  wheel
azure-mgmt-marketplaceordering    0.1.0   1.1.0  wheel
azure-mgmt-monitor                0.5.2   2.0.0  wheel
azure-mgmt-network                12.0.0  19.0.0 wheel
azure-mgmt-nspkg                  2.0.0   3.0.2  wheel
azure-mgmt-privatedns             0.1.0   1.0.0  wheel
azure-mgmt-rdbms                  1.9.0   8.0.0  wheel
azure-mgmt-recoveryservices       0.4.0   1.0.0  wheel
azure-mgmt-recoveryservicesbackup 0.6.0   0.11.0 wheel
azure-mgmt-redis                  5.0.0   12.0.0 wheel
azure-mgmt-resource               10.2.0  17.0.0 wheel
azure-mgmt-search                 3.0.0   8.0.0  wheel
azure-mgmt-servicebus             0.5.3   6.0.0  wheel
azure-mgmt-sql                    0.10.0  2.0.0  wheel
azure-mgmt-storage                11.1.0  18.0.0 wheel
azure-mgmt-trafficmanager         0.50.0  0.51.0 wheel
azure-mgmt-web                    0.41.0  2.0.0  wheel
azure-nspkg                       2.0.0   3.0.2  wheel
azure-storage                     0.35.1  0.37.0 sdist
msrest                            0.6.10  0.6.21 wheel
```

It is also very difficult to have them pinned down to patch level. If you need anything else in your environment, you'll have version conflicts very easily. The `requirements-azure.txt` seem like minimum versions required instead of actual requirements file.

Since this is used for CI, it leads to for example not noticing that install of azure-cli will break Ansible modules.

```
$ pip install azure-cli
...
$ ansible -m azure.azcollection.azure_rm_aks_info localhost
[WARNING]: No inventory was parsed, only implicit localhost is available
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.monitor.version'
localhost | FAILED! => {
    "changed": false,
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on ubuntu's Python /.../.venv/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}
```

This obsolete error message for `ansible[azure]` that has not existed for a year, comes from 
https://github.com/ansible-collections/azure/blob/619c46c5cd93cf9985a8ae5f4eb308a6e6b59a42/plugins/module_utils/azure_rm_common.py#L410.

I think that since the `ansible[azure]` has been removed, it would make sense to have a meta package to replace it. Call it `ansible-azure`, if you like. The advice to install service specific packages does not work with Ansible Azure modules, because the modules will require them all. For example the azure.azcollection.azure_rm_aks_info will error if any unrelated service specific packages are missing. For some reason it tries to import them all regardless which service you are trying to work with.

`azure-cli-core` will not do. You can test it by creating a virtual environment and trying it.

```
$ python3 -m venv .venv2
$ source .venv2/bin/activate
$ pip install ansible
...
$ pip install azure-cli-core
...
$ ansible -m azure.azcollection.azure_rm_aks_info localhost
[WARNING]: No inventory was parsed, only implicit localhost is available
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.monitor'
localhost | FAILED! => {
    "changed": false,
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on ubuntu's Python /home/kohtala/andritz/3rdparty/azure/.venv2/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}
```

**Comment by kohtala** [comment]
The newer packages installed with azure-cli fail with the azure.azcollection in these imports:

https://github.com/ansible-collections/azure/blob/619c46c5cd93cf9985a8ae5f4eb308a6e6b59a42/plugins/module_utils/azure_rm_common.py#L232-L238

It seems these imports went unused and obsolete in https://github.com/ansible/ansible/commit/26f551d1c37277e5522836d7a6cb98de42c50fb7. It would be easiest to remove them.

On quick look, it seems it would be possible to remove the other imports also by passing the first argument to `get_mgmt_svc_client` as name of the class. Would need to check how the error of missing dependency would be handled if the dependency is missing at that late moment. But implementing that would allow to install only those dependencies that are really needed and the documentation for each module would then document which dependency it has instead of some "install the world" dependency.

**Comment by Fred-sun** [comment]
@fabricat Do you still have this problem? If not, I will close it. Thank you very much!

**Comment by fabricat** [comment]
Hi @Fred-sun 
I see that on [Ansible doc](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/) (maybe an old version?) `azure >= 2.0.0` is still cited.

Anyway, if I follow the updated installation instructions on GitHub or Ansible Galaxy, the `pip install` step seems to work (sorry, I could not actually test the plugins yet).

JFYI, I still get one error from `pip` (not sure if that's trivial):

    ERROR: azure-mgmt-datalake-nspkg 3.0.1 has requirement azure-mgmt-nspkg>=3.0.0, but you'll have azure-mgmt-nspkg 2.0.0 which is incompatible.

**Comment by Fred-sun** [comment]
@fabricat 　You are using the latest requirements-azure.txt（sudo pip3 install -r　requirements-azure.txt　）, now Ansible is doing the migration, will not support Python 2.7, support Python 3.6 later versions! Thank you very much!

**Comment by mikecowie-seequent** [comment]
Hi all

Putting an agreement on this.

The packaging of the azure components required to make this work this is very hard to work with. With effort (and this thread was helpful), I can resolve specific issues, but it's just frankly poorly put together, the apparent dependecies are too vague and it's incredibly easy to install incompatible components. (In my case I'm using python 3.9 in a venv) .

Constructive ideas:
* deliver it as an rpm and dpkg for supported OS, in the same repositories as the azure cli .
* create a vendored/separated azure-ansible package with everything **inside** and nothing pulled out explicitely (and might need a little magic to get the imports to work right?)

Acknowledinhg that both the python packaging, and Microsoft Azure python SDK, both have aspects that could be improved that are hard work, but this has been an exercise in frustration.

It is not a ringing endorsement of these modules that calling Azure CLI from ansible.builtin.shell was much more productive for me.

**Comment by Fred-sun** [comment]
@fabricat Have your problems been solved? If it has been resolved, I will close it. Thank you very much!

**Comment by fabricat** [comment]
Hi @Fred-sun 
Yes, I confirm that I could follow the install/update instuctions without problems: all commands executed without errors.

Just a suggestion: reading instructions from Ansible Galaxy, it is not clear where to find the `requirements-azure.txt` file.
Maybe a link to the Github repository can help.

Thanks.
